KEY_ID = "ID"
KEY_PW = "PW"
KEY_EMAIL = "EMAIL"
KEY_PHONE = "PHONE"

KEY_REG_DATE = "REG_DATE"
KEY_MOT_DATE = "MOT_DATE"

KEY_IS_APPROVE = "IS_APPROVE"
KEY_PERMISSIONS = "PERMISSIONS"
KEY_SENIOR_ID = "SENIOR_ID"

# configs들 전부 app.configs.py에 옮겨서 사용하기
