KEY_NAME = "NAME"
KEY_ID = "ID"
KEY_PW = "PW"
KEY_EMAIL = "EMAIL"
KEY_PHONE = "PHONE"

KEY_REG_DATE = "REG_DATE"
KEY_MOD_DATE = "MOD_DATE"

KEY_IS_APPROVE = "IS_APPROVE"
KEY_PERMISSIONS = "PERMISSIONS"
KEY_RANK = "RANK"
KEY_SENIOR_ID = "SENIOR_ID"

KEY_IS_FIRST_LOGIN = "IS_FIRST_LOGIN"


PERMISSION_ADMIN = "ADMIN"
PERMISSION_OBSERVER = "OBSERVER"

PERMISSION_NAME = {
    PERMISSION_ADMIN: "관리자",
    PERMISSION_OBSERVER: "관제자",
}

# Login
LOGIN_FAIL_LIMIT = 3
PASSWORD_MIN_LENGTH = 8
CAPTCHA_LENGTH = 5

# Email Domains
ALLOW_EMAIL_DOMAINS = ["gmail.com", "naver.com", "daum.net"]

# Event Logs
KEY_EVENT_ID = "ID"
KEY_EVENT_DATE = "REG_DATE"
KEY_TARGET_ID = "TARGET_ID"
KEY_EVENT_LAT = "latitude"
KEY_EVENT_LON = "longitude"
KEY_IS_READ = "IS_READ"
KEY_EVENT_CAPTURE = "EVENT_CAPTURE"
KEY_CAPTURE_DATE = "capture_date"
KEY_EVENT_IMG_ROOT = "IMG_ROOT"

# Target profiles Logs
KEY_AGE = "AGE"
KEY_SHORT_DESC = "SHORT_DESCRIPTION"
KEY_DESC = "DESCRIPTION"
KEY_IMAGE = "IMAGE"

# User Logs
KEY_LOG_ID = "ID"
KEY_EVENT_LOG_ID = "EVENT_LOG_ID"
KEY_VIEWER_ID = "VIEWER_ID"
KEY_READ_DATE = "READ_DATE"