CAM01_URL = "http://192.168.137.159:81/stream"
IDENTIFY_THREASHOLD = 0.45
FACE_DETECTION_SIZE = (640, 640)

KEY_MATCH_RATIO = "FACE_MATCH_RATIO"
KEY_CROP = "PERSON_CROP"
KEY_BOX = "PERSON_BOX_IN_FRAME"

KEY_NAME = "NAME"
KEY_ID = "ID"
KEY_PW = "PW"
KEY_EMAIL = "EMAIL"
KEY_PHONE = "PHONE"

KEY_REG_DATE = "REG_DATE"
KEY_MOT_DATE = "MOT_DATE"

KEY_IS_APPROVE = "IS_APPROVE"
KEY_PERMISSIONS = "PERMISSIONS"
KEY_SENIOR_ID = "SENIOR_ID"

KEY_IS_FIRST_LOGIN = "IS_FIRST_LOGIN"

DELETED_ID_FILE = "deleted_id.json"


# Login

LOGIN_FAIL_LIMIT = 3
PASSWORD_MIN_LENGTH = 8
CAPTCHA_LENGTH = 5

# Email Domains
ALLOW_EMAIL_DOMAINS = ["gmail.com", "naver.com", "daum.net"]

# Event Logs
KEY_EVENT_ID = "ID"
KEY_EVENT_DATE = "REG_DATE"
KEY_TARGET_ID = "TARGET_ID"
KEY_EVENT_LAT = "latitude"
KEY_EVENT_LON = "longitude"
KEY_IS_READ = "IS_READ"

# User Logs
KEY_LOG_ID = "ID"
KEY_EVENT_LOG_ID = "EVENT_LOG_ID"
KEY_VIEWER_ID = "VIEWER_ID"
KEY_READ_DATE = "READ_DATE"